name: null-project
version: 0.1
vendor: XiaoGuo, Liu <xiaoguo.liu@canonical.com>
summary: This is the null project
description: A simple demo showing how to install a debian package
icon: icon.png

parts:
  example-part:
    plugin: nil
    stage-packages:
      - gnupg
      - wget
    organize:
      usr/bin: bin
    filesets:
      binaries:
       - bin/*
       - usr/bin/*
      headers:
       - "*.h"
       - -include
    stage:
      - $binaries
      - test/bin/test_app
      - $headers
    snap:
      - $binaries

